spring.application.name=order-service
server.port=8082

spring.config.import=optional:configserver:http://localhost:8888

resilience4j.circuitbreaker.instances.paymentService.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.paymentService.sliding-window-size=10
resilience4j.circuitbreaker.instances.paymentService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.paymentService.wait-duration-in-open-state=5s
resilience4j.circuitbreaker.instances.paymentService.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.paymentService.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.paymentService.register-health-indicator=true

management.health.circuitbreakers.enabled=true
management.endpoints.web.exposure.include=health,circuitbreakers


# ===== Retry =====
resilience4j.retry.instances.paymentService.max-attempts=3
resilience4j.retry.instances.paymentService.wait-duration=500ms
resilience4j.retry.instances.paymentService.enable-exponential-backoff=true
resilience4j.retry.instances.paymentService.exponential-backoff-multiplier=2


# ===== Bulkhead =====

resilience4j.bulkhead.instances.paymentService.max-concurrent-calls=10
resilience4j.bulkhead.instances.paymentService.max-wait-duration=0ms

# ===== TimeLimiter =====

resilience4j.timelimiter.instances.paymentService.timeout-duration=2s
resilience4j.timelimiter.instances.paymentService.cancel-running-future=true


# ===== Kafka Producer =====
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
# Payment endpoint (overridden by WireMock tests)
payment.service.url=http://localhost:8083/api/payments
