image:
  repository: ghcr.io/doaaamr1201/enterprise-ecommerce-platform/product-service
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  type: ClusterIP
  port: 8081

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 768Mi

config:
  datasourceUrl: jdbc:postgresql://postgres:5432/productdb
  redisHost: redis
  eurekaUrl: http://eureka-server:8761/eureka/

secrets:
  dbPassword: postgres

serviceAccount:
  create: true
  name: product-service-sa

namespace: ecommerce
