spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/ecommerce-platform
          jwk-set-uri: http://localhost:8090/realms/ecommerce-platform/protocol/openid-connect/certs
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product-service-v1
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/api/v1/products/**
              filters:
                - StripPrefix=0
                - AddResponseHeader=X-Platform, microservices-pro
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20
                    redis-rate-limiter.requestedTokens: 1
                    key-resolver: "#{@ipKeyResolver}"
            - id: product-service-legacy-redirect
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/api/products/**
              filters:
                - RewritePath=/api/products(?<segment>/?.*), /api/v1/products$\{segment}
                - AddResponseHeader=X-Platform, microservices-pro
                - AddResponseHeader=Deprecation, true
                - name: AddResponseHeader
                  args:
                    name: Sunset
                    value: "Thu, 31 Dec 2026 00:00:00 GMT"
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20
                    redis-rate-limiter.requestedTokens: 1
                    key-resolver: "#{@ipKeyResolver}"
            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/api/orders/**
              filters:
                - AddResponseHeader=X-Platform, microservices-pro

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info
  tracing:
    sampling:
      probability: 1.0
    export:
      zipkin:
        endpoint: http://localhost:9411/api/v2/spans
